ALG: C51
EXP_NAME: c51

PIXEL_BASED: True
NATIVE_DOWNSCALING: True

TOTAL_TIMESTEPS: 10000000
BUFFER_SIZE: 1000000
LEARNING_STARTS: 80000
TARGET_NETWORK_FREQUENCY: 10000
SCAN_STEPS: 1000
GRADIENT_STEPS: 1 # -1 == n_envs * train_freq (== collected_steps)

NUM_ENVS: 1
LEARNING_RATE: 2.5e-4
BATCH_SIZE: 32
TRAIN_FREQUENCY: 4
GAMMA: 0.99
TAU: 1.0
START_E: 1.0
END_E: 0.01
EXPLORATION_FRACTION: 0.10

N_ATOMS: 51
V_MIN: -10.0
V_MAX: 10.0
