ALG: RAINBOW
EXP_NAME: rainbow

PIXEL_BASED: False
NATIVE_DOWNSCALING: True

TOTAL_TIMESTEPS: 10000000
# BUFFER_SIZE: 1000000
BUFFER_SIZE: 100000
LEARNING_STARTS: 80000
TARGET_NETWORK_FREQUENCY: 8000 
SCAN_STEPS: 1000
GRADIENT_STEPS: 1

NUM_ENVS: 1
LEARNING_RATE: 6.25e-5 
ADAM_EPS: 1.5e-4
BATCH_SIZE: 32
TRAIN_FREQUENCY: 4
GAMMA: 0.99
TAU: 1.0

N_STEP: 3
N_ATOMS: 51
V_MIN: -10.0
V_MAX: 10.0
NOISY_SIGMA0: 0.5
PRIORITY_EXPONENT: 0.5
IS_BETA_START: 0.4
IS_BETA_END: 1.0