ALG: RAINBOW
EXP_NAME: rainbow

PIXEL_BASED: True
NATIVE_DOWNSCALING: True

TOTAL_TIMESTEPS: 10000000
BUFFER_SIZE: 100000
LEARNING_STARTS: 80000
TARGET_NETWORK_FREQUENCY: 10000 # set to 10k for better comparability to our DQN scaleups
SCAN_STEPS: 1000
GRADIENT_STEPS: 1

NUM_ENVS: 32
# LEARNING_RATE: 6.25e-5 
LEARNING_RATE: 1e-4 
ADAM_EPS: 1.5e-4
BATCH_SIZE: 256
TRAIN_FREQUENCY: 4
GAMMA: 0.99
TAU: 1.0

N_STEP: 3
N_ATOMS: 51
V_MIN: -10.0
V_MAX: 10.0
NOISY_SIGMA0: 0.5
PRIORITY_EXPONENT: 0.5
IS_BETA_START: 0.4
IS_BETA_END: 1.0