# experiment params
NAME_INITIALS: "RE"
NUM_SEEDS: 3
SEED: 1

# wandb params
WANDB_MODE: "online"  # set to online to activate wandb
ENTITY: "jaxatari"
PROJECT: "jaxtari-blines"

# where to save the params (if None, will not save)
SAVE_PATH: "./models"
# upload to huggingface
UPLOAD_MODEL: False

# default env
ENV_ID: pong

# choose mods to be active during training, default: None
TRAIN_MODS: []
# choose mods to be evaluated after training
EVAL_MODS: []

# eval every N steps during training
EVAL_DURING_TRAIN: False
EVAL_EVERY: 100 # measured in alg iterations, not env steps
# whether to capture a video during eval
CAPTURE_VIDEO: True